# Generated by Django 3.1.3 on 2020-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sapt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meli', models.CharField(max_length=10)),
                ('nameandfamily', models.CharField(max_length=150)),
                ('father', models.CharField(max_length=100)),
                ('ozviat', models.CharField(max_length=15)),
                ('nosazman', models.CharField(max_length=15)),
                ('mahalkhedmat', models.CharField(max_length=150)),
                ('nobimari', models.CharField(max_length=150)),
                ('vaziatbimari', models.CharField(max_length=10)),
                ('noestarhat', models.CharField(max_length=10)),
                ('tarmoraje', models.DateField()),
                ('taraz', models.DateField()),
                ('tarta', models.DateField()),
                ('kolestarhat', models.IntegerField()),
                ('estarhattaednashodeh', models.IntegerField()),
                ('pezeshmktaed', models.CharField(max_length=100)),
                ('shsapt', models.IntegerField()),
                ('pezeshkmoalej', models.CharField(max_length=100)),
            ],
        ),
    ]
